server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos12345

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 867466349906-kv1qaivfivc17cl13g181ssiggllv7fc.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile